server:
  root: ./public
  port: 11235

input:
  - ./src

output:
  js: ./public/app.js
  css: ./public/app.css

alias:
  theoricus: ~theoricus-www/src/theoricus
  app: ./src/app
  templates: ./src/templates

minify:
  js: true
  css: true

boot: ./src/app/app